services:
  armds:
    container_name: armds-mb
    image: marekbykowski/ubuntu-vnc:22.04-armds
    ports:
      - '8660:22'
      - '8661:5900'
      - '8662:6080'
    hostname: armds
    networks:
      - network1
    privileged: true
    volumes:
      - shared-volume-a55:/home/ubuntu/yocto/poky/arm-aem-build
      - shared-volume-a55-arm32:/home/ubuntu/yocto/poky/arm32-aem-build/
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
  a55:
    container_name: a55-mb
    image: marekbykowski/ubuntu-vnc:22.04-aem-a55
    ports:
      - '9660:22'
      - '9661:5900'
      - '9662:6080'
      - '7101:7101'
    hostname: a55
    networks:
      - network1
    privileged: true
    volumes:
      - shared-volume-a55:/home/ubuntu/yocto/poky/arm-aem-build
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
  a55arm32:
    container_name: a55arm32-mb
    image: marekbykowski/ubuntu-vnc:22.04-aem-a55-arm32
    ports:
      - '10660:22'
      - '10661:5900'
      - '10662:6080'
      - '7102:7102'
    hostname: a55
    networks:
      - network1
    privileged: true
    volumes:
      - shared-volume-a55-arm32:/home/ubuntu/yocto/poky/arm32-aem-build/
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t

volumes:
    shared-volume-a55:
    shared-volume-a55-arm32:

networks:
  network1:
    driver: bridge
