services:
  b2b-2023-1215:
    image: ${D_USER:?error}-b2b:ubuntu
    container_name: ${D_USER:?error}-b2b
    build:
      context: ./dockerfile-b2b-2023-1215
      dockerfile: Dockerfile-b2b
      #entitlements:
      #- security.insecure
      #no_cache: true
      args:
        - username=${D_USER:?error}
        - gid=${D_GID:?error}
        - uid=${D_UID:?error}
        - password=${D_PASSWORD:?error}
        - gt=${GIT_AUTH_TOKEN:?error}
        - HTTP_PROXY=${D_HTTP_PROXY:?error}
        - HTTPS_PROXY=${D_HTTPS_PROXY:?error}
    volumes:
        - ${D_HOME:?error}:${D_HOME:?error}/host
        - /lib/modules:/lib/modules
        - /boot:/boot
    ports:
      - '${D_B2B_2023_1215_SSH_PORT:?error}:22'
      - '${D_B2B_2023_1215_VNC_PORT:?error}:5900'
      - '${D_B2B_2023_1215_NOVNC_PORT:?error}:6080'
    privileged: true
    hostname: b2b
    profiles: ["b2b-2023-1215"] # Same name as the service
    networks:
      - network-b2b-yocto-ci-at-all
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t

  b2b-2025-3:
    image: ${D_USER:?error}-b2b-2025-3:ubuntu
    container_name: ${D_USER:?error}-b2b-2025-3
    build:
      context: ./dockerfile-b2b-2025-3
      dockerfile: Dockerfile-b2b-2025-3
      #entitlements:
      #- security.insecure
      #no_cache: true
      args:
        - username=${D_USER:?error}
        - gid=${D_GID:?error}
        - uid=${D_UID:?error}
        - password=${D_PASSWORD:?error}
        - gt=${GIT_AUTH_TOKEN:?error}
        - HTTP_PROXY=${D_HTTP_PROXY:?error}
        - HTTPS_PROXY=${D_HTTPS_PROXY:?error}
    volumes:
        - ${D_HOME:?error}:${D_HOME:?error}/host
        - $PWD/workdir:/home/mbykowsx/workdir   # <- We work from workdir
        - /lib/modules:/lib/modules
        - /boot:/boot
    ports:
      - '${D_B2B_2025_3_SSH_PORT:?ERROR}:22'
      - '${D_B2B_2025_3_VNC_PORT:?error}:5900'
      - '${D_B2B_2025_3_NOVNC_PORT:?error}:6080'
    privileged: true
    hostname: b2b-2025-3
    profiles: ["b2b-2025-3"] # Same name as the service
    networks:
      - network-b2b-yocto-ci-at-all
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t

  yocto-ci:
    image: ${D_USER:?error}-yocto-ci:ubuntu
    container_name: ${D_USER:?error}-yocto-ci
    build:
      context: ./dockerfile-yocto-ci
      dockerfile: Dockerfile-yocto-ci
        #entitlements:
        #- security.insecure
        #no_cache: true
      args:
        - username=${D_USER:?error}
        - gid=${D_GID:?error}
        - uid=${D_UID:?error}
        - password=${D_PASSWORD:?error}
        - gt=${GIT_AUTH_TOKEN:?error}
        - HTTP_PROXY=${D_HTTP_PROXY:?error}
        - HTTPS_PROXY=${D_HTTPS_PROXY:?error}
    volumes:
        - ${D_HOME:?error}:${D_HOME:?error}/host
        - /lib/modules:/lib/modules
        - /boot:/boot
          #- shared-volume:/home/${D_USER:?error}
    ports:
      - '${D_YOCTO_CI_SSH_PORT:?error}:22'
      - '${D_YOCTO_CI_VNC_PORT:?error}:5900'
      - '${D_YOCTO_CI_NOVNC_PORT:?error}:6080'
    privileged: true
      #environment:
      #- HTTP_PROXY=${D_HTTP_PROXY:?error}
      #- HTTPS_PROXY=${D_HTTPS_PROXY:?error}
    hostname: yocto-ci
    profiles: ["yocto-ci"] # Same name as the service
    networks:
      - network-b2b-yocto-ci-at-all
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t

  generic:
    image: ${D_USER:?error}-generic:ubuntu
    container_name: ${D_USER:?error}-generic
    build:
      context: ./dockerfile-generic
      dockerfile: Dockerfile-generic
        #entitlements:
        #- security.insecure
      no_cache: true
      args:
        - username=${D_USER:?error}
        - gid=${D_GID:?error}
        - uid=${D_UID:?error}
        - password=${D_PASSWORD:?error}
        - gt=${GIT_AUTH_TOKEN:?error}
        - HTTP_PROXY=${D_HTTP_PROXY:?error}
        - HTTPS_PROXY=${D_HTTPS_PROXY:?error}
    volumes:
        - ${D_HOME:?error}:${D_HOME:?error}/host
        - /lib/modules:/lib/modules
        - /boot:/boot
          #- shared-volume:/home/${D_USER:?error}
    ports:
      - '${D_GENERIC_SSH_PORT:?error}:22'
      - '${D_GENERIC_VNC_PORT:?error}:5900'
      - '${D_GENERIC_NOVNC_PORT:?error}:6080'
    privileged: true
      #environment:
      #- HTTP_PROXY=${D_HTTP_PROXY:?error}
      #- HTTPS_PROXY=${D_HTTPS_PROXY:?error}
    hostname: generic
    profiles: ["generic"] # Same name as the service
    networks:
      - network-b2b-yocto-ci-at-all
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t

  yocto:
    image: ${D_USER:?error}-yocto:ubuntu
    container_name: ${D_USER:?error}-yocto
    build:
      context: ./dockerfile-yocto
      dockerfile: Dockerfile-yocto
        #entitlements:
        #- security.insecure
      no_cache: true
      args:
        - username=${D_USER:?error}
        - gid=${D_GID:?error}
        - uid=${D_UID:?error}
        - password=${D_PASSWORD:?error}
        - gt=${GIT_AUTH_TOKEN:?error}
        - HTTP_PROXY=${D_HTTP_PROXY:?error}
        - HTTPS_PROXY=${D_HTTPS_PROXY:?error}
    volumes:
        - ${D_HOME:?error}:${D_HOME:?error}/host
        - /lib/modules:/lib/modules
        - /boot:/boot
          #- shared-volume:/home/${D_USER:?error}
    ports:
      - '${D_YOCTO_SSH_PORT:?error}:22'
      - '${D_YOCTO_VNC_PORT:?error}:5900'
      - '${D_YOCTO_NOVNC_PORT:?error}:6080'
    privileged: true
      #environment:
      #- HTTP_PROXY=${D_HTTP_PROXY:?error}
      #- HTTPS_PROXY=${D_HTTPS_PROXY:?error}
    hostname: yocto
    profiles: ["yocto"] # Same name as the service
    networks:
      - network-b2b-yocto-ci-at-all
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t

  tdx:
    image: ${D_USER:?error}-tdx:ubuntu
    container_name: ${D_USER:?error}-tdx
    build:
      context: ./dockerfile-tdx-ubuntu-24.04
      dockerfile: Dockerfile-tdx
        #entitlements:
        #- security.insecure
      no_cache: true
      args:
        - username=${D_USER:?error}
        - gid=${D_GID:?error}
        - uid=${D_UID:?error}
        - password=${D_PASSWORD:?error}
        - gt=${GIT_AUTH_TOKEN:?error}
        - HTTP_PROXY=${D_HTTP_PROXY:?error}
        - HTTPS_PROXY=${D_HTTPS_PROXY:?error}
    volumes:
        - ${D_HOME:?error}:${D_HOME:?error}/host
        - /lib/modules:/lib/modules
        - /boot:/boot
        - /dev:/dev
          #- shared-volume:/home/${D_USER:?error}
    ports:
      - '${D_TDX_SSH_PORT:?error}:22'
      - '${D_TDX_VNC_PORT:?error}:5900'
      - '${D_TDX_NOVNC_PORT:?error}:6080'
    privileged: true
      #environment:
      #- HTTP_PROXY=${D_HTTP_PROXY:?error}
      #- HTTPS_PROXY=${D_HTTPS_PROXY:?error}
    hostname: tdx
    profiles: ["tdx"] # Same name as the service
    #cap_add:
    #  - ALL # Needed for VFIO & device access
    #devices:
    #  - "/dev/vfio/33:/dev/vfio/33" # Map your VFIO device into container
    #  - "/dev/vfio/vfio:/dev/vfio/vfio" # VFIO control device
    networks:
      - network-b2b-yocto-ci-at-all
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
#volumes:
#    shared-volume:

networks:
  network-b2b-yocto-ci-at-all:
    driver: bridge
