FROM ubuntu:20.04

ARG username
ARG gid
ARG uid
ARG password

# default screen size
ENV XRES=1280x800x24

# Ubuntu doesn't set this var and without it avery qemu fails
ENV USER=${username}

# supress dialogue when installing tzdata
ENV TZ=Europe/Warsaw
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
#ENV DEBIAN_FRONTEND=noninteractive

RUN <<EOF
# To pass ${username} to Dockerfile go 'docker build --build-arg username=mbykowsx'
groupadd --gid ${gid} ${username}
useradd --uid ${uid} --gid ${gid} --shell /bin/bash --create-home ${username}
usermod -a -G sudo ${username}
usermod -a -G kvm ${username}
echo "${username}:${password}" | chpasswd
EOF

# This apt-conf includes the http proxy used in Intel. Run it only for Intel.
COPY apt.conf /etc/apt/

# sshd requires a log dir and when misses it fails. Add it in.
RUN mkdir -p /var/run/sshd && chmod 755 /var/run/sshd

RUN <<EOF
# esentially Yocto tools
apt-get -y update && apt-get -y install build-essential chrpath cpio debianutils diffstat file gawk \
  gcc iputils-ping libacl1 liblz4-tool python3 python3-git locales \
  python3-jinja2 python3-pexpect python3-pip python3-subunit socat texinfo unzip \
  wget xz-utils zstd
apt-get -y install sudo vim tmux gzip unzip git cpu-checker  perl libterm-readkey-perl \
 libpixman-1-0 libpixman-1-dev  libglib2.0-0 \
# required from sv
 dc time libelf1
# install GUI, vnc, novnc
apt-get install -y --no-install-recommends apt-utils sudo supervisor vim \
   openssh-server \
   xserver-xorg xvfb x11vnc dbus-x11 xfce4 \
   xfce4-terminal xfce4-xkb-plugin \
   novnc websockify
EOF

# Put MOTD in .bash_aliases
COPY .bash_aliases /home/${username}

# Copy sample qcow to have what to get started with
#COPY core-image-cxl-sdk-cxlx86-64.rootfs.wic.qcow2 /home/${username}

# install gh. in Ubuntu 20.04 it is not in apt
COPY gh_2.69.0_linux_amd64.deb /home/${username}
RUN dpkg -i /home/${username}/gh_2.69.0_linux_amd64.deb

# make /bin/sh symlink to bash instead of running dash:
RUN echo "dash dash/sh boolean false" | debconf-set-selections
RUN DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash

# Install b2b tools
#RUN mkdir -p /home/${username}/avery/2023_1215
#COPY apciexactor-2.5c.cxl.tar.gz aqcxl_sim-2023_1215.tar.gz \
#  avery_pli-2023_1128.tar.gz avery_qemu-docker.zip \
#  verdi.tar.gz vcsmx.tar.gz /tmp
#RUN for f in /tmp/*tar.gz; do tar -xzf $f -C /home/${username}/avery/2023_1215 && rm $f; done
#RUN unzip /tmp/avery_qemu-docker.zip -d /home/${username}/avery/2023_1215

# add my sys config files
COPY etc /etc

# Install firefox
RUN apt-get -y update && apt-get -y install firefox

# user config files
# terminal
COPY config/xfce4/terminal/terminalrc /home/${username}/.config/xfce4/terminal/terminalrc
# wallpaper
COPY config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml /home/${username}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
# icon theme
COPY config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml /home/${username}/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml

RUN chown -v -R ${username}:${username} /home/${username}

# ports
EXPOSE 22 5900 6080

# # default command
CMD ["/usr/bin/supervisord","-c","/etc/supervisord.conf"]
