#!/bin/bash

_DIRNAME=$(dirname -- "$0")
# verbose goes 0- crit, 1-info, 2-debug
_VERBOSE=1
_RUN=""
_BUILD=""
_COMMIT=""
_USER=""
_LOGFILE=""
_PASSWORD=password
_IMAGE="ubuntu:20.04-rc0.0"

# Instead of echo use `log <crit|info|debug> "mseg"`
# setting verosity `_VERBOSE` to the desired level.
declare -A LOG_LEVELS
LOG_LEVELS=([crit]=0 [info]=1 [debug]=2)
function log () {
	local LEVEL=${1}
	shift
	if [ ${_VERBOSE} -ge ${LOG_LEVELS[$LEVEL]} ]; then
		echo -e "${LEVEL}: $@"
	fi
}

usage() {
	cat <<- EOF
	To build image run:
		image build --user <username> --password <password>
	To run image:
		image run
	EOF
	exit 1
}

opts=$(getopt -o rbu:p:h --long run,build,user:,password:,help -n $0 -- "$@")

# set positional parameters
eval set -- "$opts"

while [[ : ]]; do
        case "$1" in
                -r | --run) _RUN=true; shift 1 ;;
                -b | --build) _BUILD=true; shift 1 ;;
                -u | --user) _USER=$2; shift 2 ;;
                -p | --password) _PASSWORD=$2; shift 2 ;;
		-h | --help) usage; shift ;;
                --) shift; break ;;
        esac
done


if [[ $1 == build ]]; then
	_BUILD=true
elif [[ $1 == run ]]; then
	_RUN=true
elif [[ $1 == commit ]]; then
	_COMMIT=true
fi

# ${var:-word} means if var is defined AND NOT EMPTY, use var; otherwise, "word"
log debug "params: --run ${_RUN:-false} --build ${_BUILD:-false} --user $_USER --password $_PASSWORD"
log debug "Remaining arguments: $@"

# Update VARs post parsing them them
[[ _RUN == true ]] && _OP=run || _OP=build
_LOGFILE=${_OP}-${_USER}-$(date +%s).log
_IMAGE=${USER}-${_IMAGE}

# Test what state the container is in, eg. running, non-existent, etc.
container_state() {
	rc=$(${_DIRNAME}/check_docker_container.sh $1)
	return $rc
}

test_if_image_already_exist() {
	docker image inspect ${_IMAGE} > /dev/null 2>&1
	rc=$?
	return $rc
}

build() {
	#log debug "${FUNCNAME[0]}"

	if test_if_image_already_exist; then
		#image exists
		log crit "Image ${_IMAGE} exists. Remove it before creating a new one!"
		log crit "\t\`docker rmi ${_IMAGE}\`"
		exit 1
	fi

	[[ $_VERBOSE -eq 2 ]] && args="--progress=plain" || args="--progress=quiet"
	args=--progress=plain

	[[ : ]] && _CACHE="" || _CACHE="--no-cache"

	log info "docker build ${_CACHE} $args \
 --build-arg username=${_USER} --build-arg gid=$(id -g) --build-arg uid=$(id -u) \
 --build-arg password=${_PASSWORD} -t ${_IMAGE} ~/docker 2>&1 |tee ${_LOGFILE}" | tee ${_LOGFILE}

	# --no-cache - slow but saves space
	docker --debug build ${_CACHE} ${arg} \
	--build-arg username=${_USER} --build-arg gid=$(id -g) --build-arg uid=$(id -u) \
	--build-arg password=${_PASSWORD} -t ${_IMAGE} ~/docker 2>&1 | tee -a ${_LOGFILE}
}

run() {
	local CONTAINER_NAME=great_day_${USER}
	container_state $CONTAINER_NAME
	rc=$?
	log debug "container_state rc $rc"
	case ${rc} in
	0)
		log info "Container $CONTAINER_NAME is running"
		docker exec -it $CONTAINER_NAME /bin/bash
		;;
	1)
		log info "Container $CONTAINER_NAME is restarting"
		;;
	2|3)
		log info "Container $CONTAINER_NAME is neither running nor exist"
		docker run --name $CONTAINER_NAME --rm -it \
			--env HTTP_PROXY==http://proxy-us.intel.com:911 \
			--env HTTPS_PROXY=http://proxy-us.intel.com:912 \
			-v $HOME:$HOME/host --privileged ${_IMAGE}
		;;
	*)
		log info "Container $CONTAINER_NAME in unknown state"
		exit
		;;
	esac
}

commit() {
	local CONTAINER_NAME=great_day_${USER}
	local CONTAINER_ID=$(docker ps --filter "name=${CONTAINER_NAME}" --format "{{.ID}}")
	local MSG=Update-$(date +%s)

	log info "docker diff ${CONTAINER_ID}"
	docker diff ${CONTAINER_ID} |head -n 2

	log info "docker commit -m ${MSG} ${CONTAINER_ID} ${_IMAGE}"
	docker commit -m "${MSG}" ${CONTAINER_ID} ${_IMAGE}

	log info "docker image history ${_IMAGE}"
	docker image history ${_IMAGE}|head -n 2
}

if [[ $_BUILD == true ]]; then
	build --user $_USER --password $_PASSWORD
elif [[ $_RUN == true ]]; then
	run
elif [[ $_COMMIT == true ]]; then
	commit
fi
