#!/bin/bash

build() {
	./image_build.sh -u kot -p p1
}

help_image_build() {
cat << 'EOF'
cd 1-docker #with Dockerfile
docker build -t ubuntu:22.04 .
# where:
#`-t` is tag
#`.` is the path where Dockerfile is
EOF
}

help_image_update() {
cat << 'EOF'
#### Terminal 1 ####
# run docker
$ docker run --rm -it -v $HOME:$HOME ubuntu:22.04
<update, eg. sudo apt-get install vim>


#### Terminal 2 ####
$ docker ps
CONTAINER ID   IMAGE          COMMAND       CREATED         STATUS         PORTS
3cdaaa4f736d   ubuntu:22.04   "/bin/bash"   5 minutes ago   Up 5 minutes

$ docker container commit -m "Add vim" 3cdaaa4f736d ubuntu:22.04
$ docker image history ubuntu:22.04
IMAGE          CREATED          CREATED BY               SIZE      COMMENT
33cfea9b3881   5 minutes ago    /bin/bash                401MB     Add vim

#### Terminal 1 ####
$ exit
EOF
}

help_image_system() {
cat << 'EOF'
docker system df
docker system df -v
docker system info
docker system prune
	-a, --all		Remove all unused images not just dangling ones
	--filter		API 1.28+ Provide filter values (e.g. label=<key>=<value>)
	-f, --force		Do not prompt for confirmation
	--volumes		Prune anonymous volumes
EOF
}

help_update_image() {
cat << 'EOF'
### Update image

Updating `image` is more a flow than running a single command.

When you update the `image` and exit the `container` you would lose all the date changed.
To prevent from it you have to commit the changes before exiting the container. To do so open
another terminal while docker is running and

[mbykowsx@GNR-JF04-5350 commands]$ docker ps                                                                                  
CONTAINER ID   IMAGE                         COMMAND       CREATED          STATUS          PORTS     NAMES                   
7bd76b49237a   mbykowsx-ubuntu:20.04-rc0.0   "/bin/bash"   14 minutes ago   Up 14 minutes             great_day_mbykowsx      

[mbykowsx@GNR-JF04-5350 commands]$ docker container diff great_day_mbykowsx      
A /var/lib/dpkg/info/man-db.triggers                  
C /var/lib/dpkg/info/hostname.list                    
C /var/lib/dpkg/info/libcanberra0:amd64.list          
C /var/lib/dpkg/info/gpg-wks-server.list              
C /var/lib/dpkg/info/libxml-sax-perl.list             
C /var/lib/dpkg/info/libalgorithm-diff-xs-perl.list   
C /var/lib/dpkg/info/libpython3-stdlib:amd64.list     
C /var/lib/dpkg/info/vim-runtime.list                 
C /var/lib/dpkg/info/libgnutls30:amd64.list           

[mbykowsx@GNR-JF04-5350 commands]$ docker commit -m "Add man pages" 7bd76b49237a mbykowsx-ubuntu:20.04-rc0.0                  
sha256:7669efdd3601c0e7b57ed90f47d6bc8d0ffbdfd54933a893e42024f95641d896                                                       

[mbykowsx@GNR-JF04-5350 commands]$ docker images                                                                              
REPOSITORY             TAG           IMAGE ID       CREATED         SIZE                                                      
mbykowsx-ubuntu        20.04-rc0.0   7669efdd3601   6 seconds ago   75.1GB                                                    
EOF
}

