#!/bin/bash

#hi - help image
hi_run_yocto_image() {
cat << 'EOF'
docker run --rm -it -p 2222:22  --env HTTP_PROXY=http://proxy-us.intel.com:911  --env HTTPS_PROXY=http://proxy-us.intel.com:912  --privileged  marekbykowski/yocto-qemu-simics:nanbield-rc0.1
EOF
}

hi_run_image() {
cat << 'EOF'
# detch (-d) with terminal (-t), keep alive (-i), then ssh
docker run --rm -it -d -p 6666:22 --env HTTP_PROXY=http://proxy-us.intel.com:911 --env HTTPS_PROXY=http://proxy-us.intel.com:912 --privileged marekbykowski/yocto-qemu-simics:nanbield-rc0.0
# same but do not detach, will prompt to terminal
docker run --rm -it -p 6666:22 --env HTTP_PROXY=http://proxy-us.intel.com:911 --env HTTPS_PROXY=http://proxy-us.intel.com:912 --privileged marekbykowski/yocto-qemu-simics:nanbield-rc0.0
# with vnc there is a supervised command, ctrl+c to exit the image
docker run --rm -p 6666:22 -p 6667:5900 --env HTTP_PROXY=http://proxy-us.intel.com:911 --env HTTPS_PROXY=http://proxy-us.intel.com:912 --privileged marekbykowski/ubuntu-vnc:22.04
EOF
}

hi_wrapup_commands() {
cat << 'EOF'
image build --user=<user> --password=<password>
image run
image commit
EOF
}

hi_build() {
cat << 'EOF'
cd 1-docker #with Dockerfile
docker build -t ubuntu:22.04 .
# where:
#`-t` is tag
#`.` is the path where Dockerfile is
EOF
}

hi_system() {
cat << 'EOF'
docker system df
docker system df -v
docker system info
docker system prune
	-a, --all		Remove all unused images not just dangling ones
	--filter		API 1.28+ Provide filter values (e.g. label=<key>=<value>)
	-f, --force		Do not prompt for confirmation
	--volumes		Prune anonymous volumes
EOF
}

hi_update() {
cat << 'EOF'
### Update image

Updating `image` is more a flow than running a single command.

When you update the `image` and exit the `container` you would lose all the date changed.
To prevent from it you have to commit the changes before exiting the container.
While docker is running Open up another and

[mbykowsx@GNR-JF04-5350 commands]$ docker ps
CONTAINER ID   IMAGE                         COMMAND       CREATED          STATUS          PORTS     NAMES
7bd76b49237a   mbykowsx-ubuntu:20.04-rc0.0   "/bin/bash"   14 minutes ago   Up 14 minutes             great_day_mbykowsx

[mbykowsx@GNR-JF04-5350 commands]$ docker container diff great_day_mbykowsx
A /var/lib/dpkg/info/man-db.triggers
C /var/lib/dpkg/info/hostname.list
C /var/lib/dpkg/info/libcanberra0:amd64.list
C /var/lib/dpkg/info/gpg-wks-server.list
C /var/lib/dpkg/info/libxml-sax-perl.list
C /var/lib/dpkg/info/libalgorithm-diff-xs-perl.list
C /var/lib/dpkg/info/libpython3-stdlib:amd64.list
C /var/lib/dpkg/info/vim-runtime.list
C /var/lib/dpkg/info/libgnutls30:amd64.list

[mbykowsx@GNR-JF04-5350 commands]$ docker commit -m "Add man pages" 7bd76b49237a mbykowsx-ubuntu:20.04-rc0.0
sha256:7669efdd3601c0e7b57ed90f47d6bc8d0ffbdfd54933a893e42024f95641d896

[mbykowsx@GNR-JF04-5350 commands]$ docker images
REPOSITORY             TAG           IMAGE ID       CREATED         SIZE
mbykowsx-ubuntu        20.04-rc0.0   7669efdd3601   6 seconds ago   75.1GB
EOF
}


hi_run() {
cat << 'EOF'
docker run --name great_day_mbykowsx --rm -it  --env HTTP_PROXY==http://proxy-us.intel.com:911  --env HTTPS_PROXY=http://proxy-us.intel.com:912  -v /home/mbykowsx:/home/mbykowsx/host --privileged <image:tag>
EOF
}

echo "run hi_wrapup_commands"
